### ISSUE TITLE
api errors

### ISSUE THREAD

**Issue by micheldumontier** [bio-ontology-research-group/aberowl-orepo#91]
Tried this query:

http://aber-owl.net/service/api/runQuery.groovy?type=subeq&query=%27organic%20chemicals%27&ontology=RH-MESH&labels=true

but getting 502 proxy error. using with another class like

http://aber-owl.net/service/api/runQuery.groovy?type=subeq&query='pharmaceutical preparations'&ontology=RH-MESH&labels=true

i don't get the results i expect

this one works : http://aber-owl.net/service/api/runQuery.groovy?type=subeq&query=%27polycyclic%20compounds%27&ontology=RH-MESH&labels=true

**Comment by leechuck** [comment]
That's an error with our proxy setup; the request is received by the server and answered as expected, but for some reason it runs in a timeout or something like that. Will have to investigate.
Also, adding "direct=true" as parameter works fine.

**Comment by leechuck** [comment]
Increasing the timeout parameter of ProxyPass directive solved the proxy error.

**Comment by leechuck** [comment]
The problem with the pharmaceutical preparations is due to two classes having the label 'pharmaceutical preparations' in MeSH, one is the expected one (http://aber-owl.net/ontology/RH-MESH#!http%3A%2F%2Fphenomebrowser.net%2Fontologies%2Fmesh%2Fmesh.owl%23D26) the other has no subclasses (http://aber-owl.net/ontology/RH-MESH#!http%3A%2F%2Fphenomebrowser.net%2Fontologies%2Fmesh%2Fmesh.owl%23D004364). It's a general problem in the RH-MESH OWL version; not sure it should or could be fixed easily in AberOWL without introducing (and automatically generating) prefixes for each URI. If you query for URIs, it all works as expected. 

For now, I don't think it's a problem in AberOWL but rather in RH-MESH (or the way it was built with duplication of labels when they occur in the general topics and specific ones), and should not be fixed in AberOWL. Please reopen if you think AberOWL should solve this issue.
